('Oppo Reno 10x zoom', 'Maecenas pulvinar lobortis est.', 5237.3, true),
('BLU Gol', 'Nullam sit amet turpis elementum ligula vehicula consequat.', 6995.0, false),
('alcatel 1S (2021)', 'Suspendisse accumsan tortor quis turpis.', 24690.0, false),
('Gionee P12', 'Integer ac neque.', 12502.0, false),
('Sony Xperia XA Dual', 'Quisque id justo sit amet sapien dignissim vestibulum.', 9642.8, false),
('Micromax Bolt Supreme Q300', 'Nulla ut erat id mauris vulputate elementum.', 4410.1, false),
('Samsung S8530 Wave II', 'Nullam porttitor lacus at turpis.', 17530.7, true),
('Archos 50 Platinum', 'Vestibulum ac est lacinia nisi venenatis tristique.', 17387.2, false),
('Samsung G800', 'Suspendisse potenti.', 10593.4, false),
('Qtek S200', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 9117.9, false),
('Oppo A12e', 'Nullam porttitor lacus at turpis.', 20997.7, true),
('OnePlus 7T Pro 5G McLaren', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 13286.4, true),
('Samsung C270', 'Nulla mollis molestie lorem.', 15117.7, false),
('alcatel OT 757', 'Maecenas pulvinar lobortis est.', 15250.0, false),
('XOLO Q800', 'Aliquam erat volutpat.', 11939.5, false),
('Allview V2 Viper X+', 'Curabitur convallis.', 12034.4, false),
('Celkon A7', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 2880.8, false),
('i-mate JASJAM', 'Aliquam sit amet diam in magna bibendum imperdiet.', 23932.5, false),
('Gionee F5', 'Morbi quis tortor id nulla ultrices aliquet.', 23580.4, false),
('Motorola W230', 'Sed accumsan felis.', 24042.2, false);
