const bodyHTMl = document.getElementById("bodychido");
console.log(bodyHTMl);

const root = document.createElement("html");
root.lang = "es";
console.log(root);
const head = document.createElement("head");
const title = document.createElement("title");
const titleText = document.createTextNode("HTMl con JS");
title.appendChild(titleText);
head.appendChild(title);
root.appendChild(head);
console.log(root);
const body = document.createElement("body");
root.appendChild(body);
console.log(root);
const h1 = document.createElement("h1");
const h1Text = document.createTextNode("Soy un H1 en una prueba tree");
h1.appendChild(h1Text);
body.appendChild(h1);
const p = document.createElement("p");
const pText = document.createTextNode("Hola Jorge te saluda un elemento p");
p.appendChild(pText);
p.style.fontWeight = "bold";
body.appendChild(p);
const img = document.createElement("img");
img.setAttribute("src","capi7.jpg");
img.setAttribute("alt", "Capibara elegido por Martha");
img.setAttribute("width", "20px");
img.setAttribute("height", "20px");
img.setAttribute("data-id", "20");
img.removeAttribute("height");
img.removeAttribute("width");
console.log(img.dataset.id);
body.appendChild(img);
console.log(img);
console.log(root);
bodyHTMl.appendChild(body);